### ISSUE TITLE
I am having an issue, $user is undefined in chatMessage.

### ISSUE THREAD

**Issue by GabMic** [ahmedkhan847/chatwithlaravelandvue#1]
```
ErrorException in ChatMessage.php line 34:
Undefined property: App\Events\ChatMessage::$user
```

the code is the same as here, how can i solve this?
Thanks.

**Comment by ahmedkhan847** [comment]
have you clone it exactly?

**Comment by GabMic** [comment]
I have downloaded it as a zip today, configured everything like it says on GitHub(by the way, you need to add that we have to install vue-resource also). added the credentials, migrated the database. and now it gives me this issue: `BroadcastException in PusherBroadcaster.php line 106:
Unknown auth_key`. what can i do now? Thanks for the help.

**Comment by ahmedkhan847** [comment]
Follow this tutorial to setup your .env filehttps://www.cloudways.com/blog/realtime-chatroom-with-laravel-vuejs-pusher/

**Comment by ahmedkhan847** [comment]
Also need to add pusher key in app.js

**Comment by GabMic** [comment]
It's not that. i have just solved it. in the config/broadcasting.php file you need to add your cluster in the options array. like so:
` 'options' => [
                'cluster'=> 'yourClusterHere(it's found in the pusher dashboard)', 
            ],`
