### ISSUE TITLE
How can we persist the data?

### ISSUE THREAD

**Issue by GabMic** [ahmedkhan847/chatwithlaravelandvue#2]
After i got this to work, i am realizing that the data is not being kept anywhere(am i wrong?).
I was wondering how can we modify/add something so that the users will have access to the information even if they are not logged in? because right now, you need to have both sides connected at the same time. 
Thanks.

**Comment by ahmedkhan847** [comment]
Yeah its not keeping it anywhere. You need to add it in database and create your own logic

**Comment by GabMic** [comment]
How can i go about it in your opinion?

**Comment by ahmedkhan847** [comment]
Save it in your database like comments

**Comment by GabMic** [comment]
I made a seperate Chat Model, and saved `$message`to a `chats` table i made with the fields drom the request. Now i want the relations of users and the messages and thats tje tricky part. I will continue to develope this. It would be great if you could do a tutorial on this exact thing in your site. I think its the last step that will make it from great to awesome! Thanks my friend.

**Comment by mombe090** [comment]
He has right please help us and show how to persist data in the database and how two fecth it
