### ISSUE TITLE
Error in the Post method of the Controller.

### ISSUE THREAD

**Issue by HerlyOlivares** [ahmedkhan847/chatwithlaravelandvue#3]
Hi, @ahmedkhan847,

I clone the code, I made a composer update and a npm install, generate the migrations, when I tried to run npm run dev, I requested npm install vue-resource and I did, after that run npm run dev, but raise the Server, access and be in the chat room and try to send a message does not do anything, revose the console and I am generano this error:

app.js:37713 POST http://localhost:8000/chat 500 (Internal Server Error)
app.js:37713 XHR finished loading: POST "http://localhost:8000/chat".
error
Response {url: "chat", ok: false, status: 500, statusText: "Internal Server Error", headers: Headers…}

When I comment the event code in the controller, it works but without transmitting through the channel of course, Vue sends the message to the view only.

event(new ChatMessage($message));

Please can you help me with that mistake, I've checked everything, but I have no idea what may be going on.

**Comment by ahmedkhan847** [comment]
Have you added Pusher details in .env file and in app.js?

**Comment by goehlemichael** [comment]
I am experiencing the same problem with the same error. I also double checked the .env and app.js

**Comment by goehlemichael** [comment]
@HerlyOlivares 

Double check your broadcasting.php and include under options where it is //:
                'cluster' => 'XXX',
                'encrypted' => 'true'
Also make sure that app.js and app2.js have the key in there as well
