### ISSUE TITLE
Blank messages are sent

### ISSUE THREAD

**Issue by vmitchell85** [ahmedkhan847/chatwithlaravelandvue#4]
If you leave the field blank and hit ENTER a blank message is sent

**Comment by fergyfresh** [comment]
Add validation for the form fields here:

chatwithlaravelandvue / app / Http / Controllers / ChatController.php 

27     public function sendMessage(Request $request) 
28     { 
29         $message = [ 
30             "id" => $request->userid, 
31             "sourceuserid" => Auth::user()->id, 
32             "name" => Auth::user()->name, 
33             "message" => $request->message 
34         ]; 
35         event(new ChatMessage($message)); 
36         return "true"; 
37     } 

You could do this I think, you want to check that the request isn't empty and only post it when its not empty: 

    public function sendMessage(Request $request)
    {
        $message = [
            "id" => $request->userid,
            "sourceuserid" => Auth::user()->id,
            "name" => Auth::user()->name,
            "message" => $request->message
        ];
        $not_empty = !empty($request->message);
        if ($not_empty) {
            event(new ChatMessage($message));
        }
        return $not_empty;
    }

You could also add it to the html at the following (resources/views/chat.blade.php)

**Comment by vmitchell85** [comment]
Thanks for the details @fergyfresh 

I wasn't clear, but I was indicating that the default validation should be changed to not allow blank messages to be sent. I cannot think of a reason to allow blank messages and I came across this repo via Twitter and noticed the issue when playing with the demo.

**Comment by fergyfresh** [comment]
I did that from my phone and do not have access to try it out. That should work though.

**Comment by ahmedkhan847** [comment]
Hi all. Sorry for late reply. I think I forget to add that validation on client side and server side. now I have added it you can take the latest pull. Simple addition for validation is:

```
 $this->validate($request, [
        'userid' => 'required',
        'message' => 'required',
        ]);
```
